"""Add invited_by_user_id and is_converted to users

Revision ID: 48f8fe797358
Revises: 25d814bc83ed
Create Date: 2024-12-16 18:48:19.560627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f8fe797358'
down_revision: Union[str, None] = '25d814bc83ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_analytics',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('total_anonymous_users', sa.Integer(), server_default='0', nullable=False),
        sa.Column('total_authenticated_users', sa.Integer(), server_default='0', nullable=False),
        sa.Column('conversion_rate', sa.String(length=10), nullable=False),
        sa.Column('inactive_users_24hr', sa.Integer(), server_default='0', nullable=False),
        sa.Column('inactive_users_48hr', sa.Integer(), server_default='0', nullable=False),
        sa.Column('inactive_users_1wk', sa.Integer(), server_default='0', nullable=False),
        sa.Column('inactive_users_1yr', sa.Integer(), server_default='0', nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # Add columns to the users table
    op.add_column('users', sa.Column('invited_by_user_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('is_converted', sa.Boolean(), server_default=sa.sql.expression.false(), nullable=False))
    # Add foreign key for invited_by_user_id
    op.create_foreign_key('fk_users_invited_by', 'users', 'users', ['invited_by_user_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'is_converted')
    op.drop_column('users', 'invited_by_user_id')
    op.drop_table('retention_analytics')
    # ### end Alembic commands ###
